export const ROLE_THRESHOLDS = {
  "Public Relations Officer": 5,
  "Election Officer": 8,
  "Deputy MLA": 10,
  "MP": 10,
  "MLA": 25,
  "Chief Secretary": 30,
  "Media Minister": 40,
  "Treasury Minister": 50,
  "District MP": 100,
};

export const CITIZEN_ROLES = [
  "Citizen",
  "Journalist",
  "Lawyer",
  "Influencer",
  "Activist",
  "Meme Creator",
];

export const INDIA_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

export const ROLE_DESCRIPTIONS: Record<string, string> = {
  Citizen: "Default political participant. Vote, comment, react.",
  Journalist: "Covers political news. Can publish Breaking News posts with viral reach.",
  Lawyer: "Provides legal challenges. Can file Legal Objections against government actions.",
  Influencer: "Social media powerhouse. Posts get 2x follower visibility boost.",
  Activist: "Protest organizer. Can start public protest events.",
  "Meme Creator": "Propaganda artist. Can submit memes to official meme wars.",
  "Public Relations Officer": "Manages party's public image.",
  "Election Officer": "Organizes district elections.",
  "Deputy MLA": "Junior district government role.",
  MP: "Full political power in district.",
  MLA: "Leads the district government.",
  "Chief Secretary": "Top administrative officer.",
  "Media Minister": "Controls district media and press.",
  "Treasury Minister": "Manages district treasury.",
  "District MP": "Highest power in district.",
};

export const ROLE_ICONS: Record<string, string> = {
  Citizen: "Users",
  Journalist: "Newspaper",
  Lawyer: "Scale",
  Influencer: "Star",
  Activist: "Megaphone",
  "Meme Creator": "Smile",
  "Public Relations Officer": "Phone",
  "Election Officer": "Vote",
  "Deputy MLA": "Building2",
  MP: "Crown",
  MLA: "Landmark",
  "Chief Secretary": "Briefcase",
  "Media Minister": "Radio",
  "Treasury Minister": "Coins",
  "District MP": "Trophy",
};
